// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoUfWkB8rjht--DxzfNsPhj2bV_pBpts0',
    appId: '1:85245065481:web:b83ea3199bc28e3de0fbd8',
    messagingSenderId: '85245065481',
    projectId: 'perfect-paws-4701d',
    authDomain: 'perfect-paws-4701d.firebaseapp.com',
    storageBucket: 'perfect-paws-4701d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJx0JZqSnLGd2YHqqU49rlcS7_PGR5bSw',
    appId: '1:85245065481:android:0a0a8a547a6bf7e7e0fbd8',
    messagingSenderId: '85245065481',
    projectId: 'perfect-paws-4701d',
    storageBucket: 'perfect-paws-4701d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH70eg_gxmFFwRi6mCsO5PeP0tecMpv_w',
    appId: '1:85245065481:ios:67485258b5be91e9e0fbd8',
    messagingSenderId: '85245065481',
    projectId: 'perfect-paws-4701d',
    storageBucket: 'perfect-paws-4701d.firebasestorage.app',
    iosBundleId: 'com.example.perfectPaws',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH70eg_gxmFFwRi6mCsO5PeP0tecMpv_w',
    appId: '1:85245065481:ios:67485258b5be91e9e0fbd8',
    messagingSenderId: '85245065481',
    projectId: 'perfect-paws-4701d',
    storageBucket: 'perfect-paws-4701d.firebasestorage.app',
    iosBundleId: 'com.example.perfectPaws',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoUfWkB8rjht--DxzfNsPhj2bV_pBpts0',
    appId: '1:85245065481:web:388c9a2cb68adad6e0fbd8',
    messagingSenderId: '85245065481',
    projectId: 'perfect-paws-4701d',
    authDomain: 'perfect-paws-4701d.firebaseapp.com',
    storageBucket: 'perfect-paws-4701d.firebasestorage.app',
  );
}
